id: litmus-judge-11
key: HZ4yclz8Lp3pUOgUcFACHcPNX6D04wL1zvPGPq2VLLg=
problem_storage_globs:
  - /home/ubuntu/problems/*
runtime:
  as_x64: /usr/bin/x86_64-linux-gnu-as
  as_x86: /usr/bin/as
  awk: /usr/bin/mawk
  cat: /usr/bin/cat
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /usr/bin/g++
  g++17: /usr/bin/g++
  g++20: /usr/bin/g++-11
  gcc: /usr/bin/gcc
  gcc11: /usr/bin/gcc
  java8: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  javac8: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  ld_x64: /usr/bin/x86_64-linux-gnu-ld
  ld_x86: /usr/bin/ld
  node: /usr/bin/node
  perl: /usr/bin/perl
  python3: /usr/bin/python3.10
  sed: /usr/bin/sed
  tclsh: /usr/bin/tclsh
