# Generated by Django 3.2.25 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0029_alter_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Follow system')], default='light', max_length=5, verbose_name='site theme'),
        ),
    ]
