# Generated by Django 3.2.25 on 2026-07-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0032_contest_late_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='학번'),
        ),
    ]
